# Allow sudo for running apt-get/brew
sudo: required
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
jdk:
  - oraclejdk8
before_script:
  - .travis/setup-env.sh
script:
  - jdk_switcher use oraclejdk8
  - ./compile.sh
after_script:
  - .travis/teardown-env.sh

# Upload to S3.
addons:
  artifacts: true
