# Allow sudo for running apt-get/brew
sudo: required
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
jdk:
  - oraclejdk8
script:
  - .travis/setup-env.sh
  - jdk_switcher use oraclejdk8
  - ./compile.sh

# Upload to S3.
addons:
  artifacts: true
