# Allow sudo for running apt-get.
sudo: required
language: cpp
compiler:
  - clang
jdk:
  - oraclejdk8
before_script:
  - .travis/setup-env.sh
script:
  - jdk_switcher use oraclejdk8
  - ./compile.sh
after_script:
  - .travis/teardown-env.sh

# Upload to Google Cloud Storage.
deploy:
  provider: gcs
  access_key_id: GOOGK4FOMGQU2NF2FMEG
  # This is encrypted, see docs.travis-ci.com/user/deployment/gcs/.
  secret_access_key:
    secure: KXlQaKk1G527mZ7hC+m8rblBZrOWQJr6uPX9M5S3XpSAehBDBQ26/pwvDutbQBolsvUfd+WgsXU28JINk89B1qA4HpNax0ucveM5C1K4mC5fR5EmtCThV4MDsmirzfVmAxUMOXowUjpyYX39+f+Yy2Y6GHhftIe9WaueCYJyg0I=
  bucket: bucket-o-bazel
addons:
  artifacts: true
