language: cpp
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler libarchive-dev
compiler:
  - clang
jdk:
  - oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - ./compile.sh
